version: "3"

env:
  CONFIG_FILE: "./config.sh"

tasks:
  default:
    desc: Run full server setup
    cmds:
      - task: base
      - task: terminfo
      - task: ssh
      - task: sudo
      - task: ufw
      - task: docker

  base:
    desc: Install base packages and dotfiles
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/base.sh'

  terminfo:
    desc: Ensure xterm-kitty terminfo is present
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/terminfo.sh'

  ssh:
    desc: Configure SSH (port, keys, disable password login)
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/ssh.sh'

  sudo:
    desc: Disable sudo password prompt
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/sudo.sh'

  ufw:
    desc: Enable and configure UFW firewall
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/ufw.sh'

  docker:
    desc: Install Docker Engine & Compose
    cmds:
      - bash -c 'source {{.CONFIG_FILE}} && exec ./install/docker.sh'
